#!/bin/bash
ls include/* > aaa
ls src/* >> aaa
ls *.cc >> aaa
cat aaa | while read line
do
    if [ "$1" != "" ]; then
        echo "$line-----------------------"
        cat $line | grep $1
        echo ""
        echo ""
    else
        echo "$line-----------------------"
        cat $line | grep Messenger
        echo ""
        echo ""
    fi
done
rm aaa
