#!/bin/bash
nipXray macs/10_00run.mac| tee results/10_00result
nipXray macs/10_01run.mac| tee results/10_01result
nipXray macs/10_02run.mac| tee results/10_02result
nipXray macs/10_03run.mac| tee results/10_03result
nipXray macs/10_04run.mac| tee results/10_04result
nipXray macs/10_05run.mac| tee results/10_05result
nipXray macs/10_06run.mac| tee results/10_06result
nipXray macs/10_07run.mac| tee results/10_07result
nipXray macs/10_08run.mac| tee results/10_08result
nipXray macs/10_09run.mac| tee results/10_09result
