#!/bin/bash
nipXray macs/10_00run| tee results/10_00result
nipXray macs/10_01run| tee results/10_01result
nipXray macs/10_02run| tee results/10_02result
nipXray macs/10_03run| tee results/10_03result
nipXray macs/10_04run| tee results/10_04result
nipXray macs/10_05run| tee results/10_05result
nipXray macs/10_06run| tee results/10_06result
nipXray macs/10_07run| tee results/10_07result
nipXray macs/10_08run| tee results/10_08result
nipXray macs/10_09run| tee results/10_09result
