#!/bin/bash
nipXray macs/10_10run.mac| tee results/10_10result
nipXray macs/10_11run.mac| tee results/10_11result
nipXray macs/10_12run.mac| tee results/10_12result
nipXray macs/10_13run.mac| tee results/10_13result
nipXray macs/10_14run.mac| tee results/10_14result
nipXray macs/10_15run.mac| tee results/10_15result
nipXray macs/10_16run.mac| tee results/10_16result
nipXray macs/10_17run.mac| tee results/10_17result
nipXray macs/10_18run.mac| tee results/10_18result
nipXray macs/10_19run.mac| tee results/10_19result
nipXray macs/10_20run.mac| tee results/10_20result
