#!/bin/bash
nipXray macs/10_10run| tee results/10_10result
nipXray macs/10_11run| tee results/10_11result
nipXray macs/10_12run| tee results/10_12result
nipXray macs/10_13run| tee results/10_13result
nipXray macs/10_14run| tee results/10_14result
nipXray macs/10_15run| tee results/10_15result
nipXray macs/10_16run| tee results/10_16result
nipXray macs/10_17run| tee results/10_17result
nipXray macs/10_18run| tee results/10_18result
nipXray macs/10_19run| tee results/10_19result
nipXray macs/10_20run| tee results/10_20result
